---
namespace: middleware_automation
name: ansible_raft
version: "1.0.0"
readme: README.md
authors:
  - Romain Pelisse <belaran@redhat.com>
  - Guido Grazioli <ggraziol@redhat.com>
description: Ansible Raft is a transformation process to turns an upstream Ansible collection (community) into a downstream one (certificed content).
license_file: "LICENSE"
tags: [collection, ansible, release, git, tools]
dependencies:
  ansible.posix: ">=1.3.0"
repository: https://github.com/ansible-middleware/ansible_raft
documentation: https://ansible-middleware.github.io/ansible_raft
homepage: https://github.com/ansible-middleware/ansible_raft
issues: https://github.com/ansible-middleware/ansible_raft/issues
build_ignore:
  - molecule
  - .github
  - '*.tar.gz'
  - '*.zip'
  - changelogs/fragments/.gitignore
  - .gitignore
  - changelogs
  - docs/_gh_include
  - docs/conf.py
  - docs/roles.rst.template
  - docs/requirements.yml
  - upstream
  - downstream
