---
- assert:
    that:
      - upstream_namespace is defined and upstream_namespace != ""
      - upstream_name is defined and upstream_name != ""
      - downstream_name is defined and downstream_name != ""
    quiet: true
    fail_msg: "Required parameters have not been provided"
