---
collections:
  - middleware_automation.ansible_raft

galaxy_info:
  role_name: ansible_raft
  namespace: middleware_automation
  author: Romain Pelisse
  description: Role designed to transform a collection from upstream to downstream
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: "2.9"

  platforms:
   - name: EL
     versions:
     - 8

  galaxy_tags:
    - redhat
    - ansible
    - collection
