---
- ansible.builtin.include_tasks: utils/check_file_exists.yml
  vars:
    path_to_file: "{{ path_to_playbook_file }}"

- ansible.builtin.include_tasks: utils/replace_name_and_namespace.yml
  vars:
    path_to_file: "{{ path_to_playbook_file }}"

#not needed - ansible.builtin.include_tasks: playbooks/defaults_to_downstream.yml
